export const GET_GAMES_REQUEST = 'GET_GAMES_REQUEST'
export const GET_GAMES_OK = 'GET_GAMES_OK '
export const GET_GAMES_FAIL= 'GET_GAMES_FAIL'

export const GET_GAME_REQUEST = 'GET_GAME_REQUEST'
export const GET_GAME_OK = 'GET_GAME_OK '
export const GET_GAME_FAIL= 'GET_GAME_FAIL'
