export const GET_TEAMS_REQUEST = 'GET_TEAMS_REQUEST'
export const GET_TEAMS_OK = 'GET_TEAMS_OK'
export const GET_TEAMS_FAIL = 'GET_TEAMS_FAIL'
export const SELECT_TEAM = 'SELECT_TEAM'

//export const TEAM_DESTROY_REQUEST = 'TEAM_DESTROY_SUCCES'
//export const TEAM_DESTROY_OK = 'TEAM_DESTROY_OK'
//export const TEAM_DESTROY_FAIL = 'TEAM_DESTROY_FAIL'
//
//export const TEAM_UPDATE_REQUEST = 'TEAM_UPDATE_REQUEST'
//export const TEAM_UPDATE_OK = 'TEAM_UPDATE_OK'
//export const TEAM_UPDATE_FAIL = 'TEAM_UPDATE_FAIL'
